# Generated by Django 4.2.2 on 2024-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_drugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('Antibiotics', 'Antibiotics'), ('Cardiology', 'Cardiology'), ('Dermatology/skin', 'Dermatology/skin'), ('Diabetology', 'Diabetology'), ('Gastroenterology', 'Gastroenterology'), ('Gynaecology', 'Gynaecology'), ('Hormones', 'Hormones'), ('Dental', 'Dental'), ('LiverDisorders', 'LiverDisorders'), ('Neurology', 'Neurology'), ('Nutritional Preparation', 'Nutritional Preparation'), ('Ophthalmology', 'Ophthalmology'), ('Pain Management', 'Pain Management'), ('Respiratory', 'Respiratory'), ('Urology', 'Urology'), ('Vaccines', 'Vaccines')], default='Antibiotics', max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pic/StockProfilePic/')),
                ('datestock', models.DateField(null=True)),
                ('expirydate', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
