# Generated by Django 4.2.2 on 2024-05-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(null=True),
        ),
    ]
