# Generated by Django 4.2.2 on 2024-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patient_age_patient_height_patient_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('RoomNo', models.IntegerField(choices=[('Cardiologist', 'Cardiologist'), ('General Physicians', 'General Physicians'), ('Dentist', 'Dentist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Respirology', 'Respirology'), ('Urology', 'Urology'), ('Gynecologist', 'Gynecologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='101', max_length=50)),
                ('RoomType', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('General Physicians', 'General Physicians'), ('Dentist', 'Dentist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Respirology', 'Respirology'), ('Urology', 'Urology'), ('Gynecologist', 'Gynecologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='General Ward', max_length=50)),
                ('allotmentDate', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('General Physicians', 'General Physicians'), ('Dentist', 'Dentist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Respirology', 'Respirology'), ('Urology', 'Urology'), ('Gynecologist', 'Gynecologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
    ]
