# Generated by Django 4.2.2 on 2024-05-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_room_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='RoomNo',
            field=models.IntegerField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109')], default='101', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='RoomType',
            field=models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('ICU(Intensive Care Unit)', 'ICU(Intensive Care Unit)'), ('CCU(Cardiac/Coronary Care Unit)', 'CCU(Cardiac/Coronary Care Unit)'), ('Operation', 'Operation'), ('Surgical', 'Surgical'), ('MaternityCare', 'MaternityCare')], default='General Ward', max_length=50),
        ),
    ]
