# Generated by Django 4.2.2 on 2024-05-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_room_status_alter_room_roomno_alter_room_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patientName',
        ),
    ]
