# Generated by Django 4.2.2 on 2024-05-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_remove_room_doctorname_remove_room_patientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='doctorName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='patientName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
