# Generated by Django 4.2.2 on 2024-05-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_room_doctorname_room_patientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
