# Generated by Django 4.2.2 on 2024-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='RoomNo',
            field=models.PositiveIntegerField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109')], default='101', max_length=50),
        ),
    ]
