# Generated by Django 4.2.2 on 2024-05-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='RoomNo',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='allotmentDate',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patientName',
        ),
    ]
