# Generated by Django 4.2.2 on 2024-05-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_remove_nurse_roomno_remove_nurse_allotmentdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patientName',
        ),
    ]
