# Generated by Django 4.2.2 on 2024-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_rename_roomtype_room_roomtype_remove_room_roomno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='room',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patientName',
        ),
    ]
