# Generated by Django 4.2.2 on 2024-05-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_remove_room_doctorid_remove_room_doctorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='doctorId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='doctorName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='patientName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
