# Generated by Django 4.2.2 on 2024-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_nurse_allotmentdate_nurse_doctorid_nurse_doctorname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='allotmentDate',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='roomno',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='roomtype',
        ),
    ]
