# Generated by Django 4.2.2 on 2024-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_remove_nurse_allotmentdate_remove_nurse_doctorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('roomno', models.IntegerField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109')], default='101', max_length=50)),
                ('roomtype', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('ICU(Intensive Care Unit)', 'ICU(Intensive Care Unit)'), ('CCU(Cardiac/Coronary Care Unit)', 'CCU(Cardiac/Coronary Care Unit)'), ('Operation', 'Operation'), ('Surgical', 'Surgical'), ('MaternityCare', 'MaternityCare')], default='General Ward', max_length=50)),
                ('allotmentDate', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
