# Generated by Django 4.2.2 on 2024-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_remove_nursedetail_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('General Physicians', 'General Physicians'), ('Dentist', 'Dentist'), ('Small Baby Care Specialist', 'Small Baby Care Specialist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Respirology', 'Respirology'), ('Urology', 'Urology'), ('Gynecologist', 'Gynecologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50),
        ),
    ]
